### ISSUE TITLE
Add `re` package to OptionsData

### ISSUE THREAD

**Issue by thammo4** [thammo4/uvatradier#22]
Setting `df=True` throws an error:

>>> options_data.get_options_symbols(symbol="QQQ", df=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.12/site-packages/uvatradier/options_data.py", line 222, in get_options_symbols
    option_df = symbol_list_to_df(option_list);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/uvatradier/options_data.py", line 191, in symbol_list_to_df
    match = re.match(r'([A-Z]+)(\d{6})([CP])(\d+)', option)
            ^^
NameError: name 're' is not defined. Did you forget to import 're'?

**Comment by thammo4** [comment]
Added import statements for datetime and re - issue fixed
