### ISSUE TITLE
Quotes.get_historical_quotes ValueError freak out when start_date=end_date

### ISSUE THREAD

**Issue by thammo4** [thammo4/uvatradier#30]
Fix the function so that it fails in a safer/more fault tolerant manner

>>> today_str = datetime.today().strftime("%Y-%m-%d");
>>> today_str
'2024-07-18'
>>> quotes.get_historical_quotes(symbol="AXP", start_date=today_str, end_date=today_str)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thammons/Desktop/msds/tradier/uvatradier/uvatradier/quotes.py", line 131, in get_historical_quotes
    return pd.DataFrame(data['history']['day']);
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pandas/core/frame.py", line 733, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pandas/core/internals/construction.py", line 503, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pandas/core/internals/construction.py", line 114, in arrays_to_mgr
    index = _extract_index(arrays)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pandas/core/internals/construction.py", line 667, in _extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index

**Comment by thammo4** [comment]
Now if start/end dates are the same, Quotes.get_historical_quotes just returns a 1 row dataframe for the start_date = end_date
